# Generated by Django 2.2.12 on 2023-07-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='std_messages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('std_standard', models.CharField(max_length=50)),
                ('head', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=350)),
            ],
        ),
    ]
